const coins = [
  { id: "bitcoin", name: "Bitcoin" },
  { id: "ethereum", name: "Etherium" },
  { id: "binancecoin", name: "Binance Coin" },
  { id: "ripple", name: "XRP" },
  { id: "tether", name: "Tether" },
  { id: "cardano", name: "Cardano" },
  { id: "dogecoin", name: "Dogecoin" },
  { id: "polkadot", name: "Polkadot" },
  { id: "uniswap", name: "Uniswap" },
  { id: "litecoin", name: "Litecoin" },
  { id: "bitcoin-cash", name: "Bitcoin Cash" },
  { id: "chainlink", name: "Chainlink" },
  { id: "solana", name: "Solana" },
  { id: "vechain", name: "VeChain" },
  { id: "theta-token", name: "Theta Network" },
  { id: "stellar", name: "Stellar" },
  { id: "filecoin", name: "Filecoin" },
  { id: "wrapped-bitcoin", name: "Wrapped Bitcoin" },
  { id: "tron", name: "TRON" },
  { id: "binance-usd", name: "Binance USD" },
  { id: "monero", name: "Monero" },
  { id: "terra-luna", name: "Terra" },
  { id: "neo", name: "NEO" },
  { id: "klay-token", name: "Klaytn" },
  { id: "pancakeswap-token", name: "PancakeSwap" },
  { id: "iota", name: "IOTA" },
  { id: "eos", name: "EOS" },
  { id: "cosmos", name: "Cosmos" },
  { id: "aave", name: "Aave" },
  { id: "bitcoin-cash-sv", name: "Bitcoin SV" },
];

export default coins;
